export type Pool = {
  tasks: string[];
  industries: string[];
  styles: string[];
  constraints: string[];
  audiences: string[];
  platforms: string[];
};

export const pools: Pool = {
  tasks: [
    "A welcome screen for someone opening the app for the very first time",
    "A home screen that shows how much money someone has right now",
    "A long form split into steps, where nothing is lost if you leave halfway",
    "A screen with nothing in it yet, that teaches you what to do first",
    "A way to search through a very long list and narrow it down",
    "A payment screen offering three different ways to pay",
    "A list of alerts, grouped so the important ones stand out",
    "A settings screen that includes a button you cannot undo",
    "A page comparing three price plans side by side",
    "A screen for taking a photo of your identity card to prove who you are",
    "A list of past payments, with a way to report one that looks wrong",
    "A monthly spending planner where leftover money carries to next month",
    "A screen showing how far along a loan request is",
    "A screen to lock a card, change its spending limit, or reset its code",
    "An invite-a-friend screen showing progress towards a reward",
    "A chat that passes you from a robot helper to a real person",
    "A screen to set a report to send itself every week",
    "A screen where you decide what each teammate is allowed to do",
    "A flow for someone who wants to stop paying for a service",
    "A screen shown after a payment fails, that helps you fix it",
    "A phone screen for setting a savings goal",
    "A screen for a shop owner to check the money they were paid",
    "A screen for reviewing payments that look suspicious",
    "A screen for uploading a document and checking the details it read",
    "A screen for swapping one currency for another at today's rate",
    "A form for reporting damage and asking an insurer to pay",
    "A screen breaking down where someone's invested money sits",
    "A screen for splitting one bill between friends",
    "A screen for setting up a payment that repeats every month",
    "A flow for closing an account and taking your data with you",
    "A screen for asking to be allowed to spend more on a card",
    "A screen for building a summary of any date range you pick",
    "A screen for saving the people you send money to often",
    "A screen for adding a second way to prove it is really you logging in",
    "A screen showing progress towards the next reward level",
    "A screen that still works when the phone has no signal",
    "A record of everything that changed and who changed it",
    "A screen where a team approves many requests at once",
    "A starting checklist for a business opening a new account",
    "A screen for sorting past spending into categories",
    "A flow for getting back into an account when you forgot the password",
    "A first-visit feed with suggestions when nothing is known about you yet",
    "A booking screen for people in two different time zones",
    "A live map showing where an order is right now",
    "A screen putting two products side by side to compare them",
    "A guided flow for asking for money back",
    "A group chat with important messages pinned to the top",
    "A screen where you arrange your own summary boxes by dragging them",
    "A screen for recording a voice message and turning it into text",
    "A screen showing money held in several different currencies",
    "A screen for registering a product with a photo of the receipt",
    "A signup for a waiting list that shows your place in the queue",
    "A screen showing exactly what you pay when moving to a bigger plan",
    "A screen for creating and revoking access codes for other software",
    "A screen for setting alerts when stock is running low",
    "A saved list of delivery addresses with one marked as usual",
    "A short survey shown right after someone finishes a task",
    "A warning that you are about to be logged out, with your work saved",
    "A second way to log in when the fingerprint scan fails",
    "A redesign of a screen built to trick people, made honest instead",
    "A settings screen for larger text, stronger colours, and less movement",
    "A screen for managing one account shared by a whole family",
    "A screen for downloading tax paperwork for a chosen year",
    "A screen comparing loan offers from different lenders",
    "A calculator with sliders showing how long savings would last",
    "A screen showing the environmental cost of what someone bought",
    "A flow for turning on a new physical card by tapping it to the phone",
    "A screen where a robot helper hands you help articles when unsure",
    "A flow for a small business proving it is a real registered company",
    "A helper that finds cheaper deals on bills you pay every month",
    "A schedule screen for staff paid by the hour",
    "A screen for claiming back money spent at work, with a photo of the receipt",
    "A checklist for a new seller joining a marketplace",
    "A guided upload for proving a payment was wrong",
    "A message explaining a rate change and what it means for your money",
    "A screen for two people agreeing who can do what on a shared account",
    "A map for finding the nearest branch or cash machine",
    "A screen tracking money sent to another country",
    "A screen for rounding up purchases and saving the difference",
    "A message telling someone their data was exposed, and what to do now",
    "A screen for choosing which companies may see your information",
    "A summary laid out so it still reads well when printed on paper",
    "A short question shown to someone about to leave for good",
    "A screen that hands you over from the website to the phone app",
  ],
  industries: [
    "An online bank","A company that lends money","A company that sells insurance",
    "A company that invests money for people","A company that handles card payments",
    "A tool for paying staff their wages","A tool for tracking deliveries",
    "A service for booking doctor appointments","An online shopping marketplace",
    "A government service website","A learning and courses website",
    "A place to buy and sell digital currency","A website for buying and renting homes",
    "An app for booking rides","A food delivery service",
    "A tool for businesses buying supplies","A tool for managing staff and benefits",
    "A phone company's own app","A website for paying electricity and water bills",
    "A website for collecting charity donations","A website for hiring freelancers",
    "A tool for tracking crops from farm to shop","A website for booking travel",
    "A tool for law firms managing cases","A service for booking vets and pet care",
    "A tool for managing shared office space","A tool for car showrooms tracking buyers",
    "A website for selling event and museum tickets","An app for paying for street parking",
  ],
  styles: [
    "Thick black outlines and hard, offset shadows",
    "Strict grid, everything lined up, size does the talking",
    "Soft and puffy, shapes that look gently pressed into the page",
    "Magazine-like, big headlines and lots of empty space",
    "Packed with information, built for people who read it all day",
    "Rounded and cheerful, with bright colours",
    "All one colour, with a single bright shade for what matters",
    "Frosted, see-through panels stacked over each other",
    "Green text on black, like an old computer screen",
    "Warm and quiet, with gentle colours that never shout",
    "Very strong colour differences, easy to read for everyone",
    "Loud like a printed poster, huge type and flat colour",
    "Charts are the main thing, everything else supports them",
    "Buttons and surfaces that look like real physical objects",
    "Shiny, busy, and over-the-top with gradients everywhere",
    "Calm and plain, soft greys and beiges, nothing loud",
    "Glowing bright colours on near-black, like a night city",
    "Looks hand-marked, as if someone scribbled notes on top",
    "Friendly flat drawings of people alongside the text",
    "Dense like a newspaper, narrow columns and thin dividing lines",
    "Soft pinks and purples fading into each other",
    "Plain and practical like an instruction manual, with stamped labels",
  ],
  constraints: [
    "You may use only two colours","No pictures or symbols allowed, words only",
    "It must all fit on one screen with no scrolling","Everything must be on a dark background",
    "You may use only three different building blocks","No photos or illustrations at all",
    "It must still work on a very narrow phone screen","Grey only, plus one colour",
    "No pop-up windows allowed","Every version of the screen must be visible together",
    "Finish it in forty-five minutes","No buttons — everything happens by swiping or dragging",
    "One typeface, at one thickness, for everything",
    "It must be fully usable without a mouse","Numbers must be the biggest thing on screen",
    "Use no more than forty words in total","Every single element must have a visible outline",
    "It must still make sense printed in black and white",
    "No scrolling — split it into pages instead","The main button must not be blue",
    "It must still work if all images fail to load","It must be laid out right to left",
  ],
  audiences: [
    "People using a smartphone for the very first time",
    "Office staff who work with numbers all day",
    "Owners of small shops and businesses",
    "Young people in their first job",
    "Workers out in the field with a weak signal",
    "Staff whose job is checking the rules are followed",
    "Older people managing their retirement money",
    "Self-employed people whose income changes every month",
    "Parents keeping track of family spending",
    "Supervisors on a warehouse floor",
    "People in villages with very slow internet",
    "People who cannot see the screen and listen instead",
    "People working through the night",
    "Students with very little money",
    "People working abroad and sending money home",
    "Busy company bosses skimming on their phone",
  ],
  platforms: ["Phone app", "Website that works on any screen", "Website for computers"],
};
